### ISSUE TITLE
Support for ES6?

### ISSUE THREAD

**Issue by bricejlin** [es-analysis/plato#127] opened 2014-12-02 20:48 UTC
Any plans of supporting ES6? We're working on a project that uses ES6 (through 6to5) and would love to be able to measure complexity based on that versus the converted ES5 code.

**Comment by Timopheym** [comment] 2015-01-22 23:31
+1, JSX support also will be great!

**Comment by martinmicunda** [comment] 2015-02-06 22:32
+1

**Comment by mfpiccolo** [comment] 2015-02-10 17:53
:+1:

**Comment by dcheng168** [comment] 2015-02-19 03:28
:+1:

**Comment by ctumolosus** [comment] 2015-03-18 21:09
:+1:

**Comment by mrichard** [comment] 2015-03-19 17:51
+1

**Comment by alanmulhall** [comment] 2015-03-25 23:07
:+1:

**Comment by ilanbiala** [comment] 2015-03-28 23:25
Support for checking .es6/.es files will be available once #153 is merged in. Statistics and proper analysis will come later when that is ready.

**Comment by Josh-a-e** [comment] 2015-04-02 16:54
+1

**Comment by chrisveness** [comment] 2015-04-04 13:08
+1

**Comment by jrodl3r** [comment] 2015-05-05 03:00
:+1:  for ES6 + JSX

**Comment by thejameskyle** [comment] 2015-05-05 16:58
@jsoverson sounds like people want this :stuck_out_tongue_winking_eye:

**Comment by jsoverson** [comment] 2015-05-05 17:27
@thejameskyle yep, i'm working on v2 now which supports modular reporters. If someone wants to update v1 with es6 support, then I'm all for it. I just can't justify splitting my effort when I already have little time to work with :-/.

**Comment by barryels** [comment] 2015-05-25 07:03
For those who don't want to wait... Here's a simple npm script to unJSXify your source, move it into a separate dir and then plato it :)

package.json:

    {
        "scripts": {
            "metrics:clean": "rm -r target/metrics/*",
            "metrics:init": "npm run metrics:clean && jsx --no-cache-dir src/js target/metrics/src/js",
            "metrics": "npm run metrics:init && plato -r -d target/metrics/report -l .jshintrc -t 'App title' -x .spec.js target/metrics/src/js"
        },
        "devDependencies": {
            "plato": "^1.5.0",
            "react-tools": "^0.13.3"
        }
    }

$ `npm run metrics`

**Comment by raido** [comment] 2015-05-26 06:57
+1

**Comment by 0xR** [comment] 2015-06-11 10:50
Could you use https://github.com/eslint/espree instead of esprima? It looks like espree exists because esprima is slow catch up to es6.

Also: +1

**Comment by 0xR** [comment] 2015-06-11 11:10
For anyone who can't wait for es6 support: You can run babel (6to5) manually on the files and then run plato on output.

Grunt config for grunt-babel:
  ``` javascript
babel: {
  options: {},
  // Copy task result to dist directory.
  plato: {
    files: [
      {
        expand: true,
        cwd: 'app',
        src: ['scripts/**/*.js'],
        dest: '.tmp/plato'
      }
    ]
  }
}
```

Grunt config for grunt-plato:
``` javascript
plato: {
  options: {
    jshint: grunt.file.readJSON('.jshintrc')
  },
  quality: {
    files: {
      'plato': ['.tmp/plato/scripts/**/*.js']
    }
  }
}
```

**Comment by raido** [comment] 2015-06-11 20:41
I tried that some time ago and you can actually get rid of the generated es6 code if you are willing to write your own reporter and add couple of if statements there.

**Comment by ctumolosus** [comment] 2015-06-23 14:31
Has anyone tried piping output from babel into plato? I would like to minimize the amount of I/O operations caused by writing/reading from disk.

**Comment by MathRobin** [comment] 2015-06-26 14:06
The problem is that Babel add a lot of complexity for its needs, you will have a not really convincing report. But it could be a great start.

**Comment by ctumolosus** [comment] 2015-06-26 14:21
Yeah, you can also use babel's runtime option to remove the fluff from compiled files. I find it to be a good start while we wait.

**Comment by ctumolosus** [comment] 2015-06-26 14:23
Currently, I'm going through Git history to generate a report over time. If I could stream the output from Babel into Plato it will really help me eliminate all the I/O ops.

**Comment by skawaguchi** [comment] 2015-08-09 23:16
+1

**Comment by valeriansaliou** [comment] 2015-08-11 07:30
+1

**Comment by wjustice** [comment] 2015-08-17 20:16
+1

**Comment by magikMaker** [comment] 2015-09-22 09:30
+1

**Comment by thejameskyle** [comment] 2015-09-22 22:11
@jsoverson Want to lock this issue? These +1s are really useless and annoying but I don't want to unsubscribe from this thread in case something does happen with it.

**Comment by miguelramos** [comment] 2015-11-11 10:14
+1

**Comment by MadRabbit** [comment] 2015-11-14 23:36
+1

**Comment by rodoabad** [comment] 2015-11-16 15:42
Please refrain from just commenting with +1s. They don't add any meaningful discussion to the issue.

**Comment by 0xR** [comment] 2015-11-16 16:33
@rodoabad this is currently the only way to display your interest on github. I like to think this helps the developers prioritising. To avoid the clutter in the comments I would advise [this chrome extension](https://chrome.google.com/webstore/detail/github-%201s/lddfkkebajnpiicnpfamebilmhamkeme).

**Comment by thejameskyle** [comment] 2015-11-16 18:03
> I like to think this helps the developers prioritizing.

As someone who helps maintain one of the [largest github projects](https://github.com/babel/babel), no it absolutely does not help with anything. I actively delete +1s on our repositories and lock issues where people are spamming us with them. We universally hate it, so just stop.

**Comment by jsoverson** [comment] 2016-07-15 18:17
supported by @devcrust in 1.6.0

**Closed by jsoverson** 2016-07-15 18:17 UTC
